version: "3.4"

services:
    app:
        container_name: "app"
        build:
            context: ./app
        image: app
        volumes:
            - ${APP_FOLDER}:/usr/src/app
        ports:
            - "8080:8080"