name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Build the Docker image
        uses: actions/checkout@v3
      - 
        name: Run the Docker image
        run: cd docker; docker-compose up -d
      - 
        name: Test
        run: docker run --rm --network container:app appropriate/curl -s --retry 10 --retry-connrefused http://localhost:4000/
