name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Build the Docker image
        uses: actions/checkout@v3
      - 
        name: Run the Docker image
        run: docker/docker-compose up -d
